name: build
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build SPA dist
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build SPA
      run: npx quasar build -m spa
    
    - name: compress dist
      run: tar czf dist.tar.gz dist
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}